os:
  - linux
services:
  - docker
before_script:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - docker manifest
  - sudo service docker restart
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - wget https://github.com/multiarch/qemu-user-static/releases/download/v2.12.0-1/qemu-arm-static -O /tmp/qemu-arm-static
  - chmod +x /tmp/qemu-arm-static

script:
  - travis_wait 30 docker build -f Dockerfile.amd64 -t $DOCKERHUB_ACCOUNT/$IMAGE_NAME:amd64 ./
  - cp /tmp/qemu-arm-static ./
  - travis_wait 60 docker build -f Dockerfile.armhf -t $DOCKERHUB_ACCOUNT/$IMAGE_NAME:armhf ./

after_success:
  - docker images
  - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ] && [ ! -z $TRAVIS_TAG ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKERHUB_ACCOUNT" -p="$DOCKERHUB_PASSWD";
    docker tag $DOCKERHUB_ACCOUNT/$IMAGE_NAME:amd64 $DOCKERHUB_ACCOUNT/$IMAGE_NAME:$TRAVIS_TAG-amd64;
    docker tag $DOCKERHUB_ACCOUNT/$IMAGE_NAME:armhf $DOCKERHUB_ACCOUNT/$IMAGE_NAME:$TRAVIS_TAG-armhf;
    docker tag $DOCKERHUB_ACCOUNT/$IMAGE_NAME:$TRAVIS_TAG-amd64 $DOCKERHUB_ACCOUNT/$IMAGE_NAME:latest-amd64;
    docker tag $DOCKERHUB_ACCOUNT/$IMAGE_NAME:$TRAVIS_TAG-armhf $DOCKERHUB_ACCOUNT/$IMAGE_NAME:latest-armhf;
    docker push $DOCKERHUB_ACCOUNT/$IMAGE_NAME:$TRAVIS_TAG-amd64;
    docker push $DOCKERHUB_ACCOUNT/$IMAGE_NAME:$TRAVIS_TAG-armhf;
    docker push $DOCKERHUB_ACCOUNT/$IMAGE_NAME:latest-amd64;
    docker push $DOCKERHUB_ACCOUNT/$IMAGE_NAME:latest-armhf;
    docker tag $DOCKERHUB_ACCOUNT/$IMAGE_NAME:amd64 $DOCKERHUB_ACCOUNT/$IMAGE_NAME:latest;
    docker push $DOCKERHUB_ACCOUNT/$IMAGE_NAME:latest;
    fi
